server:
  port: 8081
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719 加入被占用会自动从8719一次+1扫描 直到找到未被占用的端口
        port: 8719
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true
