server:
  port: 8401
spring:
  application:
    name: answer-sentinel-service
  cloud:
    discovery:
      server-addr: localhost:8488
    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        #默认8719 加入被占用会自动从8719一次+1扫描 直到找到未被占用的端口
        port: 8719
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    root: info
