server:
  port: 8000

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
      routes:
        - id: userservice_routh1 # 路由的id，没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8081 # 匹配后提供服务的路由地址
          uri: lb://userservice
          predicates:
           - Path=/user/** #断言，路径相匹配的进行路由
#           - Header=X-Request-Id ,\d+ #请求头有X-Request-Id属性并且值为整数的正则表达式
#           - Host=answer.com #请求头必须带host 为answer.com
#           - Method=Get #http方法是get才可以

        - id: orderservice_routh1 # 路由的id，没有固定的规则但要求唯一，建议配合服务名
          #uri: http://localhost:8088 # 匹配后提供服务的路由地址
          uri: lb://orderservice
          predicates:
            - Path=/order/** #断言，路径相匹配的进行路由
            #- After=2021-09-28T17:29:11.779+08:00[Asia/Shanghai] #这个时间之后可以访问，之前返回404
            # 两个时间之间
           # - Between=2021-09-28T17:29:11.779+08:00[Asia/Shanghai]，2021-09-28T17:39:11.779+08:00[Asia/Shanghai]
           # - Cookie=username,yyzz #带有cookie才可以访问 如 curl http://localhost:8000/user/1 --cookie = "username=yyzz"
#            - Header=X-Request-Id ,\d+ #请求头有X-Request-Id属性并且值为整数的正则表达式

logging:
  level:
    com.answer: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS

