spring:
  application:
    name: zk-client
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        enabled: true


        register: true
server:
  port: 8002
logging:
  level:
    com.answer: info
